# PMM (on granada testnet)
contracts:
- name: "pmm_new"
  address: "KT1B5Jg8unLXy2kvLGDEfvbcca3hQ29d8WhF"
- name: "pmm_old"
  address: "KT18sHKbZtXhXtnf6ZrHEW9VgEe2eCvRr2CS"


# HEN
#contracts:
#- name: "hen_dao"
#  address: "KT1QxLqukyfohPV5kPkw97Rs6cw1DDDvYgbB"
